### ISSUE TITLE
Problem with running the function

### ISSUE THREAD

**Issue by teanijarv** [rorytboyle/hierarchical_regression#3]
Hi! 

First of all, thank you for making this code available.

I ran the function with the example data provided, but somewhere in your diagnostics function, the expected datatype is 'dataframe', but it is 'series' instead. The error code is following: **'Series' object has no attribute 'columns'**

Any idea how to fix it? Thanks in advance!

<img width="1248" alt="Screenshot 2023-02-12 at 5 06 18 pm" src="https://user-images.githubusercontent.com/24492129/218297813-58df0355-d5ef-4f5e-af83-6be16dabd4c4.png">

**Comment by rorytboyle** [comment]
Thanks for pointing out this bug - I am not actively maintaining this code - I created it for a PhD project and made it freely available as part of the resulting publication. The purpose of this repository is to make this code available to other researchers who want to examine and use this code for similar purposes (investigate the validity of proxy measures of cognitive reserve). You can read this journal article which describes the use of this code in that project: https://doi.org/10.1186%2Fs13195-021-00870-z.

I unfortunately don't have time to pull apart the code but here's my best guess at the issue. It is likely something to do with how the sets of predictors are indexed in regression_diagnostics.py as X.columns see line 274 of your error message requires a dataframe not a series. As such, with the way the function call is currently set up, X.columns returns an error when it encounters the first element of X (a series: nba['PTS']). Maybe you could try to run it with X as a list of dataframes rather than as a list of one series and two dataframes:

X = [nba[['PTS']], nba[['PTS', 'ORB']], nba[['PTS', 'ORB', 'interaction']]]

**Comment by teanijarv** [comment]
Thanks for the quick response. I got it to work!

Changed the X just as you recommended and also the same for 'y' ->  `y = nba[['W']]`

Then there came some additional issues in diagnostics function.

Firstly the at the 'ASSUMPTION 2 - LINEARITY', after the 'else' condition when calculating Pearson's, the current code needed to be changed from `correlations = scipy.stats.pearsonr(X, y)` to `correlations = scipy.stats.pearsonr(X.iloc[:, 0], y.iloc[:, 0])`.

Secondly, at the 'ASSUMPTION 4 - MULTICOLLINEARITY', when checking if VIF is larger than 5, the current code (`vif[vif > 5]`) didn't work and I changed it to `vif[vif['VIF'] > 5]` which worked.

Also, cool paper! I'm applying this code for a study also investigating healthy older adults but for looking at various EEG measures and their relationship to paired associate learning.

**Comment by rorytboyle** [comment]
Glad it worked and thank you very much for sharing your solutions. I will implement those over the next week or so and fix the code! 

That study sounds nice, would be interested to hear what you find. During my PhD we collected an EEG dataset with n=70 older adults and a range of cognitive tasks (including Paired Associates Learning from the CANTAB) and demographics + lifestyle questionnaires. If you're interested in looking at this data, let me know and we can discuss over email! My email is rorytboyle[at]gmail.com.
